name: Deploy Front
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check SSH port reachable
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          nc -vz -w 5 ${{ secrets.DEPLOY_HOST_IP }} 1303

      - name: Install and Build
        run: |
          npm ci
          npm run build
          ls -la dist

      - name: Prepare remote folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          script: |
            # Ens assegurem que la ruta existeix i tenim permisos
            sudo mkdir -p /var/www/sims-front/dist
            sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} /var/www/sims-front
            # Netegem només el contingut per a no esborrar la carpeta que estem usant de target
            find /var/www/sims-front/dist -mindepth 1 -delete

      - name: Upload Files (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          source: "dist/*"
          target: "/var/www/sims-front/dist"
          strip_components: 1

      - name: Reload Web Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          script: |
            if sudo systemctl is-active --quiet apache2; then
              sudo systemctl reload apache2
              echo "Apache2 reloaded successfully"
            else
              echo "Apache2 is not active; attempting to start"
              sudo systemctl start apache2
            fi