name: Deploy Front
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Prepare remote folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          script: |
            # Creem la carpeta amb sudo si cal i ens assegurem que el nostre usuari en sigui l'amo
            sudo mkdir -p /var/www/sims-front/dist
            sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} /var/www/sims-front/dist
            # Netegem fitxers vells per evitar conflictes
            find /var/www/sims-front/dist -mindepth 1 -delete || true

      - name: Upload Files (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          source: "dist/*"
          target: "/var/www/sims-front/dist"
          strip_components: 1

      - name: Final Touch & Nginx Refresh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          script: |
            # Tornem la propietat a www-data perquè Nginx pugui llegir-ho sense problemes
            sudo chown -R www-data:www-data /var/www/sims-front/dist
            sudo systemctl reload nginx