name: Deploy Front
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check SSH port reachable
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          nc -vz ${{ secrets.DEPLOY_HOST_IP }} 1303

      - name: Install and Build
        run: |
          npm ci
          npm run build
          ls -la dist

      - name: Prepare remote folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          timeout: 30s
          command_timeout: 10m
          script: |
            sudo mkdir -p /var/www/sims-front/dist
            sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} /var/www/sims-front
            rm -rf /var/www/sims-front/dist/*

      - name: Upload Files (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          timeout: 60s
          source: "dist/*"
          target: "/var/www/sims-front/dist"
          strip_components: 1

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1303
          script: sudo systemctl reload nginx